events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    upstream wordpress {
        server wordpress:80;
    }

    # Configuración del servidor (HTTP y HTTPS)
    include /etc/nginx/conf.d/*.conf;
}